### ISSUE TITLE
AttributeError: module 'op25' has no attribute 'fsk4_demod_ff'

### ISSUE THREAD

**Issue by scresante** [scresante/op25#1]
`cat stderr.2                                                                                                                                                                                         [0:24:37]
Using Python /usr/bin/python
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.8.2.0
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy soapy redpitaya
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Rafael Micro R820T/2 tuner
gain: name: LNA range: start 0 stop 0 step 0
setting gain lna to 36
supported sample rates 250000-2560000 step 24000
Traceback (most recent call last):
  File "/home/shawn/Code/op25/op25/gr-op25_repeater/apps/./rx.py", line 1068, in <module>
    rx = rx_main()
  File "/home/shawn/Code/op25/op25/gr-op25_repeater/apps/./rx.py", line 975, in __init__
    self.tb = p25_rx_block(self.options)
  File "/home/shawn/Code/op25/op25/gr-op25_repeater/apps/./rx.py", line 238, in __init__
    self.open_usrp()
  File "/home/shawn/Code/op25/op25/gr-op25_repeater/apps/./rx.py", line 890, in open_usrp
    self.__set_rx_from_osmosdr()
  File "/home/shawn/Code/op25/op25/gr-op25_repeater/apps/./rx.py", line 819, in __set_rx_from_osmosdr
    self.__build_graph(self.src, capture_rate)
  File "/home/shawn/Code/op25/op25/gr-op25_repeater/apps/./rx.py", line 315, in __build_graph
    self.demod = p25_demodulator.p25_demod_cb( input_rate = capture_rate,
  File "/home/shawn/Code/op25/op25/gr-op25_repeater/apps/p25_demodulator.py", line 273, in __init__
    p25_demod_base.__init__(self, if_rate=if_rate, symbol_rate=symbol_rate, filter_type=filter_type)
  File "/home/shawn/Code/op25/op25/gr-op25_repeater/apps/p25_demodulator.py", line 167, in __init__
    self.fsk4_demod = op25.fsk4_demod_ff(autotuneq, self.if_rate, self.symbol_rate)
`

**Comment by scresante** [comment]
The build and the make install work fine, I think it's a local installation problem with the make install defaulting to /usr/local

**Comment by scresante** [comment]
trying again with ` cmake ../ -DCMAKE_INSTALL_PREFIX="/usr" ` outta build

**Comment by scresante** [comment]
the failure of this import shouldn't happen , the     self.fsk4_demod = op25.fsk4_demod_ff(autotuneq, self.if_rate, self.symbol_rate)
AttributeError: module 'op25' has no attribute 'fsk4_demod_ff'
 is the problem, but importing op25 on the system shows that that exists

**Comment by scresante** [comment]
this problem exists even if `cmake ../ -DCMAKE_INSTALL_PREFIX="/usr" `

**Comment by scresante** [comment]
there's a problem in rx.py I haven't figured out exactly what it is yet

**Comment by scresante** [comment]
WHOA! ./rx.py works! it's the arguments that are causing fails!
